apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
spec:
  containers:
    - image: gcr.io/google/postgresql
      name: postgres
      env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: password
      volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumes:
    - name: postgres-data
      gcePersistentDisk:
        pdName: postgres-gce-disk
        fsType: ext4