# Generated by Django 2.1 on 2018-09-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrolanding',
            name='email',
            field=models.EmailField(error_messages={'blank': 'Email vazio', 'invalid': 'Email inválido', 'null': 'Email nulo', 'unique': 'Email já cadastrado'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='cadastrolanding',
            name='nome',
            field=models.CharField(error_messages={'blank': 'Nome vazio'}, max_length=120),
        ),
    ]
